name: Pull Request flow

on: [pull_request]

jobs:
  build-project:
    name: Build application
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, 'ci: version bump')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      # From now you can access the version

      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}

      - name: Instal YARN dependencies
        run: yarn install

      - name: Build project for windows
        run: yarn build
