name: Release flow

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-project:
    name: Build and release application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instal YARN dependencies
        run: yarn install

      - name: "cat package.json"
        run: cat ./package.json

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ${{github.run_number}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "cat package.json"
        run: cat ./package.json

      - name: Build project for windows
        run: yarn build:win

      - name: Zip the files
        uses: papeloto/action-zip@v1
        with:
          files: dist/win-ia32-unpacked
          dest: connect-marketing.zip

      - name: Release project files to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.run_number}}
          name: Release ${{github.run_number}}
          files: connect-marketing.zip
